---
## Execute this from a trusted workstation as:
## BW_HOST=https://bitwarden.com BW_USER=user@example.com BW_PASS="Master Password" envsubst < secret.yaml | kubectl replace --force -f -
apiVersion: v1
kind: Secret
type: Opaque
immutable: true
metadata:
  name: env
  namespace: bitwarden-api
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-options: Prune=false
stringData:
  BW_HOST: "$BW_HOST"
  BW_USER: "$BW_USER"
  BW_PASS: "$BW_PASS"
