---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - application.yaml
  - secretstores.yaml

commonLabels:
  app.kubernetes.io/part-of: external-secrets
  app.kubernetes.io/managed-by: Kustomize
  app.kubernetes.io/version: v0.9.20

namespace: external-secrets
