apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
spec:
  provider:
    webhook:
      url: http://bitwarden-api.bitwarden-api.svc.cluster.local:8087/object/item/{{ .remoteRef.key }}
      result:
        jsonPath: $.data.login.{{ .remoteRef.property }}
      headers:
        Content-Type: application/json
metadata:
  name: bitwarden-login
  labels:
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/part-of: external-secrets
    app.kubernetes.io/component: secret-store
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
spec:
  provider:
    webhook:
      url: http://bitwarden-api.bitwarden-api.svc.cluster.local:8087/object/item/{{ .remoteRef.key }}
      result:
        jsonPath: $.data.fields[?@.name=="{{ .remoteRef.property }}"].value
      headers:
        Content-Type: application/json
metadata:
  name: bitwarden-fields
  labels:
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/part-of: external-secrets
    app.kubernetes.io/component: secret-store
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
spec:
  provider:
    webhook:
      url: http://bitwarden-api.bitwarden-api.svc.cluster.local:8087/object/item/{{ .remoteRef.key }}
      result:
        jsonPath: $.data.notes
      headers:
        Content-Type: application/json
metadata:
  name: bitwarden-notes
  labels:
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/part-of: external-secrets
    app.kubernetes.io/component: secret-store
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
spec:
  provider:
    webhook:
      url: http://bitwarden-api.bitwarden-api.svc.cluster.local:8087/object/attachment/{{ .remoteRef.property }}?itemid={{ .remoteRef.key }}
      result: {}
      headers:
        Content-Type: application/octet-stream
metadata:
  name: bitwarden-attachments
  labels:
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/part-of: external-secrets
    app.kubernetes.io/component: secret-store
