---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  url: https://argocd.home.philipdouglass.com
  statusbadge.enabled: "true"
  exec.enabled: "true"
  exec.shells: "bash,sh,powershell,cmd"
