---
apiVersion: v1
kind: Secret
metadata:
  name: argocd-apps
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  project: default
  url: https://github.com/philipsd6/argocd-apps.git
