---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ingress.yaml
  - argocd-repo-creds.yaml
  - argocd-repositories.yaml
  - application.yaml
  - applicationset.yaml

commonAnnotations:
  app.kubernetes.io/part-of: argocd

namespace: argocd

patches:
  - path: service-patch.yaml
  - path: argocd-cm-patch.yaml
